# Generated by Django 5.2 on 2025-04-19 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount_100kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='city',
            field=models.CharField(db_index=True, default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='price_per_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
