# Generated by Django 5.2 on 2025-04-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfm', '0002_transaction_amount_100kg_transaction_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='loyalty_points',
            field=models.PositiveIntegerField(default=0, help_text='Loyalty points for this transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='product_type',
            field=models.CharField(blank=True, db_index=True, help_text='Potato variety/type', max_length=100, null=True),
        ),
    ]
